# Generated by Django 3.0.3 on 2020-02-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('jokeType', models.CharField(max_length=50)),
                ('joke',models.CharField(max_length=500)),
                ('setup', models.CharField(max_length=500)),
                ('flags',models.CharField(max_length=500)),
                ('delivery', models.CharField(max_length=500)),
                ('isNSFW', models.CharField(max_length=25)),
                ('isReligious', models.CharField(max_length=25)),
                ('isRacist',models.CharField(max_length = 25)),
                ('isPolitical', models.CharField(max_length=25)),
                ('isSexist', models.CharField(max_length=25)),
                ('idNum', models.IntegerField(default=0)),
            ],
        ),
    ]
