# Generated by Django 3.0.3 on 2020-03-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200302_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='isNSFW',
            field=models.BooleanField(max_length=200),
        ),
        migrations.AlterField(
            model_name='joke',
            name='isPolitical',
            field=models.BooleanField(max_length=200),
        ),
        migrations.AlterField(
            model_name='joke',
            name='isRacist',
            field=models.BooleanField(max_length=200),
        ),
        migrations.AlterField(
            model_name='joke',
            name='isReligious',
            field=models.BooleanField(max_length=200),
        ),
        migrations.AlterField(
            model_name='joke',
            name='isSexist',
            field=models.BooleanField(max_length=200),
        ),
    ]
