# Generated by Django 3.0.3 on 2020-04-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200303_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='delivery',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='joke',
            name='joke',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='joke',
            name='setup',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
